### ISSUE TITLE
LM-Studio fails to import GGUF data

### ISSUE THREAD

**Issue by sais-github** [lmstudio-ai/lmstudio-bug-tracker#131] opened 2024-09-24 08:16 UTC
The model on huggingface has a chat template embedded but LM-Studio is failing to import the info or even recognize it as qwen2

![image](https://github.com/user-attachments/assets/8293b118-7f5a-4d37-a456-0be89baa4180)
![image](https://github.com/user-attachments/assets/a469106a-d792-44aa-95cb-fd148f3698d5)

CPU: 5600G
RAM: 32GB - 28GB Usable
GPU1: RTX 2080
GPU2: GTX 1660 Super
GPU3: Vega-7 ((I-GPU) Not used by LM-Studio)
OS: Windows 11 23H2

**Comment by sais-github** [comment] 2024-09-24 08:18
It also fails to import the basic info like context length: 
![image](https://github.com/user-attachments/assets/a21e0cbd-6c2f-4a0b-8388-b2be1e1234dc)
And the Jinja template: 
![image](https://github.com/user-attachments/assets/8506a1e9-c8e5-4428-9636-9e916b01057e)

**Comment by yagil** [comment] 2024-09-24 14:27
Confirmed, I see it too. Looks like a GGUF parsing issue, investigating

**Comment by yagil** [comment] 2024-09-26 17:43
Fixed in 0.3.2 Build 6, available here: https://lmstudio.ai/beta-releases

**Closed** 2024-10-14 00:06 UTC
Labels: bug
